name: Cleanup

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

permissions:
  contents: read
  actions: write

jobs:
  cleanup-workflow-runs:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2.0.6
        with:
          retain_days: 0
          keep_minimum_runs: 3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
